export default [
  {
    login: 'rupam4',
    id: 17108594,
    node_id: 'MDQ6VXNlcjE3MTA4NTk0',
    avatar_url: 'https://avatars0.githubusercontent.com/u/17108594?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/rupam4',
    html_url: 'https://github.com/rupam4',
    followers_url: 'https://api.github.com/users/rupam4/followers',
    following_url: 'https://api.github.com/users/rupam4/following{/other_user}',
    gists_url: 'https://api.github.com/users/rupam4/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/rupam4/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/rupam4/subscriptions',
    organizations_url: 'https://api.github.com/users/rupam4/orgs',
    repos_url: 'https://api.github.com/users/rupam4/repos',
    events_url: 'https://api.github.com/users/rupam4/events{/privacy}',
    received_events_url: 'https://api.github.com/users/rupam4/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'o976166544',
    id: 20622180,
    node_id: 'MDQ6VXNlcjIwNjIyMTgw',
    avatar_url: 'https://avatars2.githubusercontent.com/u/20622180?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/o976166544',
    html_url: 'https://github.com/o976166544',
    followers_url: 'https://api.github.com/users/o976166544/followers',
    following_url: 'https://api.github.com/users/o976166544/following{/other_user}',
    gists_url: 'https://api.github.com/users/o976166544/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/o976166544/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/o976166544/subscriptions',
    organizations_url: 'https://api.github.com/users/o976166544/orgs',
    repos_url: 'https://api.github.com/users/o976166544/repos',
    events_url: 'https://api.github.com/users/o976166544/events{/privacy}',
    received_events_url: 'https://api.github.com/users/o976166544/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'MohZ13',
    id: 24503167,
    node_id: 'MDQ6VXNlcjI0NTAzMTY3',
    avatar_url: 'https://avatars3.githubusercontent.com/u/24503167?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/MohZ13',
    html_url: 'https://github.com/MohZ13',
    followers_url: 'https://api.github.com/users/MohZ13/followers',
    following_url: 'https://api.github.com/users/MohZ13/following{/other_user}',
    gists_url: 'https://api.github.com/users/MohZ13/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/MohZ13/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/MohZ13/subscriptions',
    organizations_url: 'https://api.github.com/users/MohZ13/orgs',
    repos_url: 'https://api.github.com/users/MohZ13/repos',
    events_url: 'https://api.github.com/users/MohZ13/events{/privacy}',
    received_events_url: 'https://api.github.com/users/MohZ13/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'jake100',
    id: 5789813,
    node_id: 'MDQ6VXNlcjU3ODk4MTM=',
    avatar_url: 'https://avatars1.githubusercontent.com/u/5789813?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jake100',
    html_url: 'https://github.com/jake100',
    followers_url: 'https://api.github.com/users/jake100/followers',
    following_url: 'https://api.github.com/users/jake100/following{/other_user}',
    gists_url: 'https://api.github.com/users/jake100/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/jake100/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/jake100/subscriptions',
    organizations_url: 'https://api.github.com/users/jake100/orgs',
    repos_url: 'https://api.github.com/users/jake100/repos',
    events_url: 'https://api.github.com/users/jake100/events{/privacy}',
    received_events_url: 'https://api.github.com/users/jake100/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'dalinhuang99',
    id: 6508763,
    node_id: 'MDQ6VXNlcjY1MDg3NjM=',
    avatar_url: 'https://avatars2.githubusercontent.com/u/6508763?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/dalinhuang99',
    html_url: 'https://github.com/dalinhuang99',
    followers_url: 'https://api.github.com/users/dalinhuang99/followers',
    following_url: 'https://api.github.com/users/dalinhuang99/following{/other_user}',
    gists_url: 'https://api.github.com/users/dalinhuang99/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/dalinhuang99/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/dalinhuang99/subscriptions',
    organizations_url: 'https://api.github.com/users/dalinhuang99/orgs',
    repos_url: 'https://api.github.com/users/dalinhuang99/repos',
    events_url: 'https://api.github.com/users/dalinhuang99/events{/privacy}',
    received_events_url: 'https://api.github.com/users/dalinhuang99/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'rushitbhadaniya',
    id: 32771921,
    node_id: 'MDQ6VXNlcjMyNzcxOTIx',
    avatar_url: 'https://avatars3.githubusercontent.com/u/32771921?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/rushitbhadaniya',
    html_url: 'https://github.com/rushitbhadaniya',
    followers_url: 'https://api.github.com/users/rushitbhadaniya/followers',
    following_url: 'https://api.github.com/users/rushitbhadaniya/following{/other_user}',
    gists_url: 'https://api.github.com/users/rushitbhadaniya/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/rushitbhadaniya/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/rushitbhadaniya/subscriptions',
    organizations_url: 'https://api.github.com/users/rushitbhadaniya/orgs',
    repos_url: 'https://api.github.com/users/rushitbhadaniya/repos',
    events_url: 'https://api.github.com/users/rushitbhadaniya/events{/privacy}',
    received_events_url: 'https://api.github.com/users/rushitbhadaniya/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'raj1997',
    id: 22416962,
    node_id: 'MDQ6VXNlcjIyNDE2OTYy',
    avatar_url: 'https://avatars2.githubusercontent.com/u/22416962?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/raj1997',
    html_url: 'https://github.com/raj1997',
    followers_url: 'https://api.github.com/users/raj1997/followers',
    following_url: 'https://api.github.com/users/raj1997/following{/other_user}',
    gists_url: 'https://api.github.com/users/raj1997/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/raj1997/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/raj1997/subscriptions',
    organizations_url: 'https://api.github.com/users/raj1997/orgs',
    repos_url: 'https://api.github.com/users/raj1997/repos',
    events_url: 'https://api.github.com/users/raj1997/events{/privacy}',
    received_events_url: 'https://api.github.com/users/raj1997/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'naushad-madakiya',
    id: 8583183,
    node_id: 'MDQ6VXNlcjg1ODMxODM=',
    avatar_url: 'https://avatars0.githubusercontent.com/u/8583183?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/naushad-madakiya',
    html_url: 'https://github.com/naushad-madakiya',
    followers_url: 'https://api.github.com/users/naushad-madakiya/followers',
    following_url: 'https://api.github.com/users/naushad-madakiya/following{/other_user}',
    gists_url: 'https://api.github.com/users/naushad-madakiya/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/naushad-madakiya/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/naushad-madakiya/subscriptions',
    organizations_url: 'https://api.github.com/users/naushad-madakiya/orgs',
    repos_url: 'https://api.github.com/users/naushad-madakiya/repos',
    events_url: 'https://api.github.com/users/naushad-madakiya/events{/privacy}',
    received_events_url: 'https://api.github.com/users/naushad-madakiya/received_events',
    type: 'User',
    site_admin: false
  }
];