const mockUser = {
  login: 'neelkanthjdabhi',
  id: 16976355,
  node_id: 'MDQ6VXNlcjE2OTc2MzU1',
  avatar_url: 'https://avatars2.githubusercontent.com/u/16976355?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/neelkanthjdabhi',
  html_url: 'https://github.com/neelkanthjdabhi',
  followers_url: 'https://api.github.com/users/neelkanthjdabhi/followers',
  following_url: 'https://api.github.com/users/neelkanthjdabhi/following{/other_user}',
  gists_url: 'https://api.github.com/users/neelkanthjdabhi/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/neelkanthjdabhi/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/neelkanthjdabhi/subscriptions',
  organizations_url: 'https://api.github.com/users/neelkanthjdabhi/orgs',
  repos_url: 'https://api.github.com/users/neelkanthjdabhi/repos',
  events_url: 'https://api.github.com/users/neelkanthjdabhi/events{/privacy}',
  received_events_url: 'https://api.github.com/users/neelkanthjdabhi/received_events',
  type: 'User',
  site_admin: false,
  name: 'Neelkanth J. Dabhi ',
  company: 'Earth',
  blog: 'http://neelkanthjdabhi.github.io/',
  location: 'Halifax, Canada',
  email: null,
  hireable: true,
  bio: 'I\'m a software engineer based in Halifax, NS.',
  twitter_username: null,
  public_repos: 13,
  public_gists: 0,
  followers: 8,
  following: 27,
  created_at: '2016-01-30T17:07:36Z',
  updated_at: '2020-08-15T17:59:38Z'
};

export default mockUser;